// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcfile.proto

package hello

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc7b0ca143987db, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type HelloResponse struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	Number               []int32  `protobuf:"varint,4,rep,packed,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc7b0ca143987db, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *HelloResponse) GetNumber() []int32 {
	if m != nil {
		return m.Number
	}
	return nil
}

type IntTrans struct {
	Input1               int64    `protobuf:"varint,1,opt,name=Input1,proto3" json:"Input1,omitempty"`
	Input2               int64    `protobuf:"varint,2,opt,name=Input2,proto3" json:"Input2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntTrans) Reset()         { *m = IntTrans{} }
func (m *IntTrans) String() string { return proto.CompactTextString(m) }
func (*IntTrans) ProtoMessage()    {}
func (*IntTrans) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc7b0ca143987db, []int{2}
}

func (m *IntTrans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntTrans.Unmarshal(m, b)
}
func (m *IntTrans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntTrans.Marshal(b, m, deterministic)
}
func (m *IntTrans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntTrans.Merge(m, src)
}
func (m *IntTrans) XXX_Size() int {
	return xxx_messageInfo_IntTrans.Size(m)
}
func (m *IntTrans) XXX_DiscardUnknown() {
	xxx_messageInfo_IntTrans.DiscardUnknown(m)
}

var xxx_messageInfo_IntTrans proto.InternalMessageInfo

func (m *IntTrans) GetInput1() int64 {
	if m != nil {
		return m.Input1
	}
	return 0
}

func (m *IntTrans) GetInput2() int64 {
	if m != nil {
		return m.Input2
	}
	return 0
}

type ResRes struct {
	IntRes               int64    `protobuf:"varint,1,opt,name=IntRes,proto3" json:"IntRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResRes) Reset()         { *m = ResRes{} }
func (m *ResRes) String() string { return proto.CompactTextString(m) }
func (*ResRes) ProtoMessage()    {}
func (*ResRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dc7b0ca143987db, []int{3}
}

func (m *ResRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResRes.Unmarshal(m, b)
}
func (m *ResRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResRes.Marshal(b, m, deterministic)
}
func (m *ResRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResRes.Merge(m, src)
}
func (m *ResRes) XXX_Size() int {
	return xxx_messageInfo_ResRes.Size(m)
}
func (m *ResRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ResRes.DiscardUnknown(m)
}

var xxx_messageInfo_ResRes proto.InternalMessageInfo

func (m *ResRes) GetIntRes() int64 {
	if m != nil {
		return m.IntRes
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "hello.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "hello.HelloResponse")
	proto.RegisterType((*IntTrans)(nil), "hello.IntTrans")
	proto.RegisterType((*ResRes)(nil), "hello.ResRes")
}

func init() { proto.RegisterFile("grpcfile.proto", fileDescriptor_2dc7b0ca143987db) }

var fileDescriptor_2dc7b0ca143987db = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x5b, 0x63, 0x42, 0x1c, 0xac, 0xc2, 0x58, 0x24, 0xe4, 0x14, 0xf6, 0x62, 0xf1, 0x10,
	0x30, 0x1e, 0x04, 0xc1, 0x83, 0x37, 0x7b, 0xdd, 0xfa, 0x05, 0xfa, 0x67, 0x8c, 0x81, 0x75, 0x77,
	0xdd, 0xdd, 0x08, 0xfd, 0xf6, 0x92, 0xcd, 0x58, 0xdb, 0x5b, 0x7e, 0xbf, 0xbc, 0x07, 0xf3, 0x16,
	0xae, 0x5a, 0x67, 0xb7, 0x1f, 0x9d, 0xa2, 0xda, 0x3a, 0x13, 0x0c, 0xa6, 0x9f, 0xa4, 0x94, 0x11,
	0xf7, 0x70, 0xf9, 0x36, 0x7c, 0x48, 0xfa, 0xee, 0xc9, 0x07, 0x2c, 0x21, 0x6f, 0x1d, 0x51, 0xe8,
	0x74, 0x5b, 0x4c, 0xab, 0xe9, 0xe2, 0x42, 0x1e, 0x58, 0xbc, 0xc0, 0x8c, 0xb3, 0xde, 0x1a, 0xed,
	0x09, 0xe7, 0x90, 0x3a, 0xb2, 0x6a, 0xcf, 0xc9, 0x11, 0xf0, 0x16, 0x32, 0xdd, 0x7f, 0x6d, 0xc8,
	0x15, 0xe7, 0x55, 0xb2, 0x48, 0x25, 0x93, 0x78, 0x86, 0x7c, 0xa9, 0xc3, 0xbb, 0x5b, 0x6b, 0x3f,
	0x64, 0x96, 0xda, 0xf6, 0xe1, 0x21, 0x56, 0x13, 0xc9, 0x74, 0xf0, 0x4d, 0x71, 0x76, 0xe4, 0x1b,
	0x51, 0x41, 0x26, 0xc9, 0x4b, 0xe2, 0x66, 0x90, 0xe4, 0xff, 0x9b, 0x03, 0x35, 0x96, 0x87, 0xac,
	0xc8, 0xfd, 0x74, 0x5b, 0xc2, 0x27, 0xc8, 0x57, 0xeb, 0x7d, 0x54, 0x78, 0x53, 0xc7, 0xb1, 0xf5,
	0xf1, 0xd2, 0x72, 0x7e, 0x2a, 0xc7, 0x49, 0x62, 0x82, 0x77, 0x90, 0xbc, 0xee, 0x76, 0x78, 0xcd,
	0xbf, 0xff, 0x4e, 0x2e, 0x67, 0x2c, 0xc6, 0x3b, 0xc4, 0x64, 0x93, 0xc5, 0x87, 0x7c, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x43, 0x9a, 0x8d, 0x45, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Add(ctx context.Context, in *IntTrans, opts ...grpc.CallOption) (*ResRes, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Add(ctx context.Context, in *IntTrans, opts ...grpc.CallOption) (*ResRes, error) {
	out := new(ResRes)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	Add(context.Context, *IntTrans) (*ResRes, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntTrans)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Add(ctx, req.(*IntTrans))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloService_SayHello_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _HelloService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcfile.proto",
}
